Techiva Bloggers: data model
fobadara/techiva-bloggers pull request #3
Opened 2022-05-05 16:07 UTC by fobadara

The following instructions were followed for this milestone:

Be sure to reference the [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png) from the sneak peek if you have any questions about table or column names or data relationships.

- Build your project schema.
    - Create and run the necessary migration files.
    - Table and column names should match the ERD diagram.
        - note: photo for users table should be a link to an image
    - Foreign keys should be included.
    - All columns that are foreign keys should have a corresponding index.

2022-05-05 16:50 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

![](https://media.giphy.com/media/cE02lboc8JPO/giphy.gif)
 @fobadara  ✋🏼 

#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.



### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._


___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-05-05 16:50 UTC, ahmetbozaci commented on db/schema.rb
> +  end
- [ ] Table and column names should match the ERD diagram.  It should be author_id
[Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/creating_data_model_project.md#:~:text=Table%20and%20column%20names%20should%20match%20the%20ERD%20diagram.)

2022-05-05 16:50 UTC, ahmetbozaci commented on db/schema.rb
> +  end
- [ ] Table and column names should match the ERD diagram.  It should be author_id
[Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/creating_data_model_project.md#:~:text=Table%20and%20column%20names%20should%20match%20the%20ERD%20diagram.)

2022-05-05 16:50 UTC, ahmetbozaci commented on db/schema.rb
> +    t.index ["user_id"], name: "index_posts_on_user_id"
- [ ] Table and column names should match the ERD diagram.  It should be author_id
[Requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/creating_data_model_project.md#:~:text=Table%20and%20column%20names%20should%20match%20the%20ERD%20diagram.)

2022-05-05 16:50 UTC, ahmetbozaci commented on db/schema.rb
> +  end
- [ ] Users' table should include name, photo and bio columns. Please add it.

2022-05-05 16:50 UTC, ahmetbozaci commented on db/migrate/20220505142007_create_users.rb
> +      t.integereger :posts_counter
- [ ] It should be an `integer`. Please fix it.

2022-05-05 16:50 UTC, ahmetbozaci commented on db/migrate/20220505152424_create_comments.rb
> +      t.string :text
The text type should be a `text`. Please change it.

2022-05-05 16:50 UTC, ahmetbozaci commented on db/migrate/20220505152800_create_post.rb
> +      t.string :text
- [ ] The title type should be a string, text type should be a text. Please change it.

2022-05-06 10:39 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @fobadara 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Github inline comments feature is used properly.
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-09 11:54 UTC, merged